(() => {
  "use strict";
  const A = window.AF;
  A.renderAdmin = async () => {
    clearInterval(A.countdown); const {data}=await A.sb.auth.getSession(),session=data.session; if(!session){location.hash="#admin-login";return;}
    let result; try{result=await A.call("admin-orders",{action:"list"},session.access_token);}catch(error){if(["invalid_auth","not_admin"].includes(error.code)){await A.sb.auth.signOut();A.toast(error.message);location.hash="#admin-login";return;}A.app.innerHTML=`${A.header()}<main class="center-page"><section class="card login-card"><h1>加载失败</h1><p>${A.escape(error.message)}</p><button class="btn btn-outline btn-block" data-route="admin">重试</button></section></main>`;return;}
    A.app.innerHTML=`${A.header('<button id="adminLogout" class="btn btn-outline btn-small">退出</button>')}<main class="page"><div class="admin-title"><div><h1>订单管理</h1><p>${A.escape(result.admin.display_name)}</p></div><div class="actions"><button id="refreshAdmin" class="btn btn-outline">刷新</button><button id="newOrder" class="btn btn-primary">新建订单</button></div></div><section class="card table-card">${result.orders.length?A.orderTable(result.orders):'<div class="empty">暂无订单</div>'}</section></main>`;
    document.getElementById("adminLogout").onclick=async()=>{await A.sb.auth.signOut();location.hash="#admin-login";};
    document.getElementById("refreshAdmin").onclick=A.renderAdmin; document.getElementById("newOrder").onclick=A.openCreateOrder;
    document.querySelectorAll("[data-admin-action]").forEach(b=>b.onclick=()=>A.runAdminAction(b.dataset.adminAction,b.dataset.orderId));
  };
  A.orderTable = orders => `<div class="table-wrap"><table><thead><tr><th>订单</th><th>套餐</th><th>状态</th><th>登录</th><th>到期</th><th>操作</th></tr></thead><tbody>${orders.map(o=>`<tr><td><div class="order-main"><b>${A.escape(o.customer_name)}</b><small>${A.escape(o.order_code)}</small></div></td><td>${A.escape(o.plan_name)}</td><td>${A.statusBadge(o.status)}</td><td>${A.escape(A.assistText[o.assist_status]||o.assist_status)}</td><td>${o.expires_at?A.formatDate(o.expires_at):"—"}</td><td><div class="actions">${A.orderActions(o)}</div></td></tr>`).join("")}</tbody></table></div>`;
  A.actionButton=(action,id,label,cls)=>`<button class="btn btn-small ${cls}" data-admin-action="${action}" data-order-id="${id}">${label}</button>`;
  A.orderActions=o=>{const b=[];if(o.assist_status==="requested")b.push(A.actionButton("process_assistance",o.id,"处理登录","btn-soft"));if(o.assist_status==="processing")b.push(A.actionButton("complete_assistance",o.id,"完成登录","btn-success"));if(o.assist_status==="ready"&&o.status==="waiting")b.push(A.actionButton("start",o.id,"开始","btn-primary"));if(o.status==="active")b.push(A.actionButton("pause",o.id,"暂停","btn-warning"));if(o.status==="paused")b.push(A.actionButton("resume",o.id,"恢复","btn-success"));if(["waiting","active","paused"].includes(o.status)){b.push(A.actionButton("extend",o.id,"延期","btn-outline"),A.actionButton("reset_code",o.id,"重置码","btn-outline"),A.actionButton("end",o.id,"结束","btn-danger"));}return b.join("")||"—";};
  A.runAdminAction=async(action,orderId)=>{const{data}=await A.sb.auth.getSession(),token=data.session?.access_token;if(!token)return A.route();const payload={action,orderId};if(action==="extend"){const v=prompt("延期多少分钟？","60");if(v===null)return;payload.minutes=Number(v);}if(action==="end"&&!confirm("确定结束该订单吗？"))return;try{const r=await A.call("admin-orders",payload,token);if(action==="reset_code")A.showCredentials("",r.accessCode,"访问码已重置");else A.toast("操作成功");A.renderAdmin();}catch(e){A.toast(e.message);}};
  A.openCreateOrder=()=>{A.modal.innerHTML=`<div class="modal-backdrop"><section class="card modal"><div class="modal-head"><div><h2>新建订单</h2><p>访问码将在创建后显示一次</p></div><button class="close" data-close>×</button></div><form id="createOrderForm" class="form"><div class="form-row"><div class="field"><label>客户名称</label><input name="customerName" required maxlength="80"></div><div class="field"><label>联系方式</label><input name="contact" maxlength="120"></div></div><div class="form-row"><div class="field"><label>套餐名称</label><input name="planName" value="24 小时" required maxlength="80"></div><div class="field"><label>时长（分钟）</label><input name="durationMinutes" type="number" min="1" max="525600" value="1440" required></div></div><div class="field"><label>备注</label><textarea name="notes" maxlength="1000"></textarea></div><div id="createError" class="error"></div><button class="btn btn-primary btn-block" type="submit">创建订单</button></form></section></div>`;A.modal.querySelector("[data-close]").onclick=A.closeModal;document.getElementById("createOrderForm").onsubmit=A.createOrder;};
  A.createOrder=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector("button[type=submit]"),err=document.getElementById("createError"),v=new FormData(form),{data}=await A.sb.auth.getSession();button.disabled=true;err.textContent="";try{const r=await A.call("admin-orders",{action:"create",customerName:v.get("customerName"),contact:v.get("contact"),planName:v.get("planName"),durationMinutes:Number(v.get("durationMinutes")),notes:v.get("notes")},data.session.access_token);A.showCredentials(r.order.order_code,r.accessCode,"订单已创建");}catch(e){err.textContent=e.message;button.disabled=false;}};
})();
